src/Entity/Realisation.php
<?php

namespace App\Entity;

use App\Repository\RealisationRepository;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RealisationRepository::class)
 */
class Realisation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $websiteLink;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $githubLink;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ImageLink;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $priory;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getWebsiteLink(): ?string
    {
        return $this->websiteLink;
    }

    public function setWebsiteLink(?string $websiteLink): self
    {
        $this->websiteLink = $websiteLink;

        return $this;
    }

    public function getGithubLink(): ?string
    {
        return $this->githubLink;
    }

    public function setGithubLink(?string $githubLink): self
    {
        $this->githubLink = $githubLink;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getPriory(): ?int
    {
        return $this->priory;
    }

    public function setPriory(?int $priory): self
    {
        $this->priory = $priory;

        return $this;
    }

    public function getImageLink()
    {
        return $this->ImageLink;
    }

    public function setImageLink($ImageLink)
    {
        $this->ImageLink = $ImageLink;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="date")
     */
    private $DateOfBirth;

    /**
     * @ORM\Column(type="integer")
     */
    private $age;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nationality;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $niveau;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $university;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $formation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $resume;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phoneNumber;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)

     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->DateOfBirth;
    }

    public function setDateOfBirth(\DateTimeInterface $DateOfBirth): self
    {
        $this->DateOfBirth = $DateOfBirth;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    public function setNationality(string $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    public function getNiveau(): ?string
    {
        return $this->niveau;
    }

    public function setNiveau(string $niveau): self
    {
        $this->niveau = $niveau;

        return $this;
    }

    public function getUniversity(): ?string
    {
        return $this->university;
    }

    public function setUniversity(string $university): self
    {
        $this->university = $university;

        return $this;
    }

    public function getFormation(): ?string
    {
        return $this->formation;
    }

    public function setFormation(?string $formation): self
    {
        $this->formation = $formation;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(?string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getResume(): ?string
    {
        return $this->resume;
    }

    public function setResume(?string $resume): self
    {
        $this->resume = $resume;

        return $this;
    }

    public function eraseCredentials(){}

    public function getSalt(){}

    public function getRoles()
    {
        return ['ROLE_USER'];
    }

    public function getUsername(){
        return $this->getEmail();
    }

    public function getUserIdentifier()
    {
        return $this->getEmail();
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Realisation;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;

use Symfony\Component\Routing\Annotation\Route;

use App\Entity\User;
use App\Form\ContactType;
use App\Repository\CompetencesRepository;
use App\Repository\RealisationRepository;
use App\Repository\UserRepository;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(UserRepository $userRepository, RealisationRepository $realisationRepository, CompetencesRepository $competencesRepository, Request $request, MailerInterface $mailer): Response
    {
        $user = $userRepository->findAll(); 
        $realisations = $realisationRepository->findAll(); 
        $competences = $competencesRepository->findAll();

        $contact = new Contact();
       

        $form = $this->createForm(ContactType::class, $contact);

        $form->handleRequest($request);

    

        if($form->isSubmitted() && $form->isValid()){
            $contact->setCreatedAt(new \DateTime());
        
            $email_html = '<div style="margin:10px;padding:10pxl font-family: verdana">
	
            <h3 style="color: #001478; text-align: center; margin-top:20px;">Message de '.$contact->getName().'</h3>
            <h4 style="color: #001478; text-align: center; margin-top:20px;">Expediteur: <a style="text-decoration:none" href="mailto:'.$contact->getSender().'">'.$contact->getSender().'</h4>
            <div>
                    <p style="padding: 20px; font-size: 18px; font-family: verdana">'.$contact->getMessage().'</p>
                    
                    <p style="padding: 10px; font-size: 18px; font-family: verdana">Envoyé le '.$contact->getCreatedAt()->format('d/m/Y').'</p>
            </div>
            
        </div>
        ';

            $mail = (new Email())
            ->from('contact@ngamcode.com')
            ->to('ngamcode@gmail.com')
            ->subject('Nouveau message sur ton portfolio')
            ->html($email_html)
         ;
            $mailer->send($mail);

            $this->addFlash('success', 'Votre message a été envoyé avec succès! Merci');
        }

        return $this->render('home/index.html.twig', [
            'user' => $user[0],
            'realisations'=>$realisations,
            'competences'=>$competences,
            'form'=>$form->createView()
        ]);
    }

    /**
     * @Route("realisation/{id}/show", name="show_detail")
     */

     public function getRealisation(Realisation $realisation){
         
        return new JsonResponse(array(
            'result' => 1,
            'id' => $realisation->getId(),
            'title'=>$realisation->getTitle(),
            'description'=>$realisation->getDescription(),
            'websiteLink'=>$realisation->getWebsiteLink(),
            'githubLink'=>$realisation->getGithubLink(),
            'imageLink'=>$realisation->getImageLink(),
        ));
     }

}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %} 

{% endblock %}

{% block body %}
    
    
    <div class="pro-opa"></div>




    <nav class="navbar">
        <div class="max-width">
            <div class="logo"><a href="#">{{user.firstName}} {{user.lastName}}<span></span></a></div>
            <ul class="menu">
                <li><a href="#home" class="menu-btn li-active">Acceuil</a></li>
                <li><a href="#about" class="menu-btn">A propos</a></li>
                <li><a href="#services" class="menu-btn">Réalisations</a></li>
                <li><a href="#skills" class="menu-btn">Compétences</a></li>
                <!-- <li><a href="#teams" class="menu-btn">Teams</a></li> -->
                <li><a href="#contact" class="menu-btn">Contact</a></li>
            </ul>
            <div class="menu-btn">
                <i class="fas fa-bars"></i>
            </div>
        </div>
    </nav>
    
    {% for message in app.flashes('success') %}
        <div class="alert-success">
            <p>{{ message }} <i class="fas fa-window-close alert_close" id = "alert_close"></i></p>
        </div>
    {% endfor %}
    <section class="home" id="home">
        <div class="max-width">
            <div class="home-content">
                <div class="text-2">{{user.title | raw}}</div>
                 <div class="text-3"><span class="typing"></span></div>
                {# <div class="text-3"><span class=""></span></div> #}

                <div id="image_1" style="display:none">
                    <img src="{{asset('Assets/images/image_1.png')}}" class="my-photo" alt="photo" />
                </div>
                <a href="#contact">Contactez-moi</a> 
            </div>
        </div>


    </section>

    <section class="services" id="services">
            <div class="max-width">

            <h2 class="title">Mes réalisations</h2>
            <div class="serv-content">

            {% for realisation in realisations %}
                <div class="card" ref="{{realisation.id}}">
                    <div class="box">
                        {# <i class="fas fa-paint-brush"></i> #}
                        {% if realisation.imageLink %}
                            <img src="{{asset('uploads/images/')}}{{realisation.imageLink}}" style="width:80px" alt="logo - projet" />
                        {% endif %}
                        <div class="text">{{realisation.title}}</div>
                         
                        <p>{{realisation.description|length > 130 ? realisation.description|slice(0, 130) ~ '...' : realisation.description  | raw }}</p>
                        <button class="btn-show" id="btn-show" ref="{{realisation.id}}">Voir les détails</button>

                         
   
 
                    </div>
                </div>    
            {% endfor %}  
            <div class="project-content">
                <div class="close-project" style="float:right"><i class="far fa-window-close" style="color:#1a2352; font-size:30px; cursor:pointer"></i></div>
                <div class="project"></div>
            </div>     
            </div>
        </div>
    </section>



    <section class="skills" id="skills">
        <div class="max-width">
            <h2 class="title">Mes compétences</h2>
            <div class="skills-content">
                <div class="column left" style="font-size: 14px">
                    <div class="text">Résumé</div>
                    <p>{{user.resume | raw}}</p>

                </div>
                <div class="column right">
                {% for competence in competences %}
                    <div class="bars">
                        <div class="info">
                            <span>{{competence.name}}</span>
                            <span>{{competence.value}}%</span>
                        </div>
                        <div class="line {{competence.label}}"></div>
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </section>

    <section class="about" id="about">
        <div class="max-width">
            <h2 class="title">A propos de moi</h2>
            <div class="about-content">
                <div class="column left">
                    <img src="{{asset('Assets/images/identity.jpg')}}" alt="">
                </div>
                <div class="column right">
                    <div class="text">Je suis {{user.firstName }} {{user.lastName }} | {{user.age}} ans</div>
                    <p>{{user.description  | raw}}</p>
                    {# <a href="#">Télécharger mon CV</a> #}
                </div>
            </div>
        </div>
    </section>
     <section class="contact" id="contact">
        <div class="max-width">
            <h2 class="title">Contactez-moi</h2>
            <div class="contact-content">
                <div class="column left">
                    {# <div class="text">Get in Touch</div> #}
                    <p>Pour toute informations complémentaires, Veillez laisser un message</p>
                    <div class="icons">
                        <div class="row">
                            <i class="fas fa-user"></i>
                            <div class="info">
                                <div class="head">Nom & Prénom</div>
                                <div class="sub-title">{{user.lastName}} {{user.firstName}}</div>
                            </div>
                        </div>
                        <div class="row">
                            <i class="fas fa-map-marker-alt"></i>
                            <div class="info">
                                <div class="head">Addresse</div>
                                <div class="sub-title">{{user.adress}}</div>
                            </div>
                        </div>
                        <div class="row">
                            <i class="fas fa-envelope"></i>
                            <div class="info">
                                <div class="head">Email</div>
                                <div class="sub-title">{{user.email}}</div>
                            </div>
                        </div>
                         <div class="row">
                            <i class="fas fa-phone"></i>
                            <div class="info">
                                <div class="head">Téléphone</div>
                                <div class="sub-title">{{user.phoneNumber}}</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="column right">
                    <div class="text">Laissez un message !</div>
                {# {{ form_start(form) }}

                    {{ form_row(form.name, {'attr':{'class':'form-control field'}}) }}
                    {{ form_row(form.sender, {'attr':{'class':'form-control field'}}) }}
                    {{ form_row(form.subject, {'attr':{'class':'form-control field'}}) }}
                    {{ form_row(form.message, {'attr':{'class':'form-control field'}}) }}
            

                    <div style="text-align:center; margin-top:20px"> 
                        <button type="submit" class="btn btn-primary">Enregistrer</button>
                    </div>
                {{ form_end(form) }} #}


                    {{form_start(form)}}
                        
                            {{ form_label(form.name, 'Prénom et NOM: ') }}
                            {{form_widget(form.name,{'attr':{'placeholder': 'Prenom NOM', 'class':'field name'}}) }}
                       
                            {{ form_label(form.sender, 'Adresse E-mail: ') }}
                            {{form_widget(form.sender,{'attr':{'placeholder': 'Adresse E-mail: ', 'class':'field email'}}) }}

                         
                            {{ form_label(form.message, 'Message: ') }}
                            {{form_widget(form.message,{'attr':{'placeholder': 'Message', 'class':'field textarea', 'rows':'10', 'cols': '30'}}) }}
                      
                         <div class="button-area">
                            <button type="submit">Envoyer</button>
                        </div>
                    {{form_end(form)}}
                    {# <form action="#">
                        <div class="fields">
                            <div class="field name">
                                <input type="text" placeholder="Nom et prénom" required>
                            </div>
                            <div class="field email">
                                <input type="email" placeholder="Adresse e-mail" required>
                            </div>
                        </div>
                        <div class="field">
                            <input type="text" placeholder="Objet" required>
                        </div>
                        <div class="field textarea">
                            <textarea cols="30" rows="10" placeholder="Votre message.." required></textarea>
                        </div>
                        <div class="button-area">
                            <button type="submit">Envoyer</button>
                        </div>
                    </form> #}
                </div>
            </div>
        </div>
    </section>

    <div class="scroll-up-btn show">
        <i class="fas fa-angle-up"></i>
    </div>

     <div class="scroll-down-btn show">
        <i class="fas fa-angle-down"></i>
    </div>


{% endblock %}